In [73]:
import numpy as np
# import arrange as np

arr = np.arange(-1, -10, -1)

print(arr)

[-1 -2 -3 -4 -5 -6 -7 -8 -9]


In [42]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [45]:
arr = np.arange(1, 13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# 1. Student Marks
# Create an array of 24 student IDs using arange(). 
# Create 24 equally spaced marks between 35 and 95 using linspace(). 
# Reshape both arrays into a 4 × 6 structure representing 4 classes with 6 students each.

In [84]:
stu = np.arange(1, 25)

print(stu)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [106]:
np.linspace(35, 95, 24)

array([35.        , 37.60869565, 40.2173913 , 42.82608696, 45.43478261,
       48.04347826, 50.65217391, 53.26086957, 55.86956522, 58.47826087,
       61.08695652, 63.69565217, 66.30434783, 68.91304348, 71.52173913,
       74.13043478, 76.73913043, 79.34782609, 81.95652174, 84.56521739,
       87.17391304, 89.7826087 , 92.39130435, 95.        ])

In [109]:
print(stu.reshape(4, 6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [87]:
# 2. Temperature Analysis

# Generate 30 time points using arange() and 30 equally spaced temperature values between 20°C and 40°C using linspace().

# Reshape both into 5 × 6 arrays representing 5 days with 6 readings per day.

In [90]:
temp = np.arange(1, 31)

print(temp)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [92]:
print(np.linspace(20, 40, 30))

[20.         20.68965517 21.37931034 22.06896552 22.75862069 23.44827586
 24.13793103 24.82758621 25.51724138 26.20689655 26.89655172 27.5862069
 28.27586207 28.96551724 29.65517241 30.34482759 31.03448276 31.72413793
 32.4137931  33.10344828 33.79310345 34.48275862 35.17241379 35.86206897
 36.55172414 37.24137931 37.93103448 38.62068966 39.31034483 40.        ]


In [94]:
print(temp.reshape(5, 6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [95]:
# 3. Sales Dataset

# Generate 48 product IDs starting from 1001 using arange().

# Generate 48 equally spaced sales values between ₹5,000 and ₹50,000 using linspace().

# Reshape both into 4 × 12 arrays representing 4 months and 12 products.

In [97]:
sal_d = np.arange(1, 49)
print(sal_d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [99]:
print(np.linspace(5000, 50000, 48))

[ 5000.          5957.44680851  6914.89361702  7872.34042553
  8829.78723404  9787.23404255 10744.68085106 11702.12765957
 12659.57446809 13617.0212766  14574.46808511 15531.91489362
 16489.36170213 17446.80851064 18404.25531915 19361.70212766
 20319.14893617 21276.59574468 22234.04255319 23191.4893617
 24148.93617021 25106.38297872 26063.82978723 27021.27659574
 27978.72340426 28936.17021277 29893.61702128 30851.06382979
 31808.5106383  32765.95744681 33723.40425532 34680.85106383
 35638.29787234 36595.74468085 37553.19148936 38510.63829787
 39468.08510638 40425.53191489 41382.9787234  42340.42553191
 43297.87234043 44255.31914894 45212.76595745 46170.21276596
 47127.65957447 48085.10638298 49042.55319149 50000.        ]


In [101]:
print(sal_d.reshape(4, 12))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45 46 47 48]]
