In [31]:
# What is Broadcasting?

"""
Broadcasting in NumPy allows us to perform arithmetic operations on arrays of different 
shapes without reshaping them. It automatically adjusts the smaller array to match the larger 
array's shape by replicating its values along the necessary dimensions. This makes element-wise 
operations more efficient by reducing memory usage and eliminating the need for loops.
"""

import numpy as np

In [32]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],     
    [70, 80, 90]
])

x = np.array([1, 2, 3])

print(arr + x)

[[11 22 33]
 [41 52 63]
 [71 82 93]]


In [33]:
print(arr + 10)

[[ 20  30  40]
 [ 50  60  70]
 [ 80  90 100]]


In [34]:
print(arr // 10)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
np.sum(arr, axis=0) # axis = 0 denoted to 'Y axis' and axis= 1 denoted to 'X axis'

array([120, 150, 180])

In [36]:
np.max(arr)

np.int64(90)

In [37]:
np.mean(arr)

np.float64(50.0)

In [38]:
np.std(arr)

np.float64(25.81988897471611)

In [40]:
np.min(arr)

np.int64(10)

In [41]:
a = np.array([10, 20, 30, 40, 8, 22, 92])
np.argmin(a)

np.int64(4)

In [43]:
np.argmax(a)

np.int64(6)

In [63]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],     
    [70, 80, 90]
])

# arr.reshape(9)
"""
To flatten an array in NumPy means to collapse a multi-dimensional array into a single 
dimension (a 1D array)
"""
arr.flatten()

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [51]:
print(arr.T) 
# Transpoart to convert the rows into columns and columns into rows

[[10 40 70]
 [20 50 80]
 [30 60 90]]


In [58]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [60]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])