In [1]:
# What is Broadcasting?

"""
Broadcasting in NumPy allows us to perform arithmetic operations on arrays of different 
shapes without reshaping them. It automatically adjusts the smaller array to match the larger 
array's shape by replicating its values along the necessary dimensions. This makes element-wise 
operations more efficient by reducing memory usage and eliminating the need for loops.
"""

import numpy as np

In [2]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],     
    [70, 80, 90]
])

x = np.array([1, 2, 3])

print(arr + x)

[[11 22 33]
 [41 52 63]
 [71 82 93]]


In [3]:
print(arr + 10)

[[ 20  30  40]
 [ 50  60  70]
 [ 80  90 100]]


In [4]:
print(arr // 10)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
np.sum(arr, axis=0) # axis = 0 denoted to 'Y axis' and axis= 1 denoted to 'X axis'

array([120, 150, 180])

In [6]:
np.max(arr)

np.int64(90)

In [7]:
np.mean(arr)

np.float64(50.0)

In [8]:
np.std(arr)

np.float64(25.81988897471611)

In [9]:
np.min(arr)

np.int64(10)

In [10]:
a = np.array([10, 20, 30, 40, 8, 22, 92])
np.argmin(a)

np.int64(4)

In [11]:
np.argmax(a)

np.int64(6)

In [12]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],     
    [70, 80, 90]
])

# arr.reshape(9)
"""
To flatten an array in NumPy means to collapse a multi-dimensional array into a single 
dimension (a 1D array)
"""
arr.flatten()

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [13]:
print(arr.T) 
# Transpoart to convert the rows into columns and columns into rows

[[10 40 70]
 [20 50 80]
 [30 60 90]]


In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [15]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [17]:
import numpy as np

In [22]:
np.random.randint(1, 10, 6)

array([1, 2, 5, 4, 1, 3], dtype=int32)

In [26]:
marks = np.array([65, 70, 81, 90, 56])

print(marks[marks >= 40]) # marks[marks >= 40] this is a boolean filtering they doesn't show 'True 7 False' values

[65 70 81 90 56]


In [27]:
import numpy as np

# Original Array
arr = np.array([10, 20, 30])

# Create a view and a copy
arr_view = arr.view()
arr_copy = arr.copy()

# Modify the original array
arr[0] = 99

print(arr_view) # Output: [99, 20, 30] (Changes reflected)
print(arr_copy) # Output: [10, 20, 30] (Stays independent)

# Check data ownership
print(arr_view.base) # Output: [99, 20, 30] (Points to parent array)
print(arr_copy.base) # Output: None


[99 20 30]
[10 20 30]
[99 20 30]
None


In [29]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

column_stack = np.column_stack((arr1, arr2, arr3))
print(column_stack)

h_stack = 

[[1 4 7]
 [2 5 8]
 [3 6 9]]
