In [5]:
import numpy as np

In [6]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([3, 4, 5, 6, 7, 8])
print(a + b)
print(a.shape)
print(a.size)
print(a[1:6])

[ 4  6  8 10 12 14]
(6,)
6
[2 3 4 5 6]


In [22]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print(arr)
print(arr[1][3]) #print(arr[1, 3])
print(arr.shape)
print(arr.size)

[[1 2 3 4]
 [5 6 7 8]]
8
(2, 4)
8


In [36]:
arr = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])
print(arr.size)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

8
(2, 2, 2)
3
int64


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr.dtype)

int64


In [11]:
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

# array [rows_start: rows_stop, column_start: column_stop]

print(arr[:2, 1:3])

[[20 30]
 [60 70]]


In [23]:
print(arr[1:, 2:3])

[[ 70]
 [110]]


In [22]:
print(arr[::, ::3])

[[ 10  40]
 [ 50  80]
 [ 90 120]]


In [28]:
print(arr[::-1, ::-1])

[[120 110 100  90]
 [ 80  70  60  50]
 [ 40  30  20  10]]


In [ ]:
# Q9. Array se ye sub-array extract karo:
20  30  40
70  80  90
120 130 140

# Q10. Sirf rows 2–4 aur columns 2–4 extract karo.

# Q11. First 3 rows ke last 2 columns extract karo.

# Q12. Last 3 rows ke first 2 columns extract karo.

# Q13. Array ki alternate rows extract karo.
# 10  20  30  40  50
# 110 120 130 140 150
# 210 220 230 240 250

# Q14. Array ki alternate columns extract karo.

# Q15. First 4 rows aur alternate columns extract karo.

In [34]:
arr = np.array([
    [10, 20,  30,  40, 50],
    [60, 70,  80,  90, 100],
    [110, 120, 130, 140, 150]
])

print(arr[::, 1:4])

[[ 20  30  40]
 [ 70  80  90]
 [120 130 140]]


In [8]:
arr = np.array([
    [10, 20,  30,  40, 50],
    [60, 70,  80,  90, 100],
    [110, 120, 130, 140, 150],
    [160, 70, 180, 190, 200],
    [210, 220, 230, 240, 250]
])

print(arr[2::2, 2::2])

[[130 150]
 [230 250]]


In [54]:
print(arr[:3, -2:])

[[ 40  50]
 [ 90 100]
 [140 150]]


In [58]:
print(arr[-3:, :2])

[[110 120]
 [160  70]
 [210 220]]


In [61]:
print(arr[::2, :])

[[ 10  20  30  40  50]
 [110 120 130 140 150]
 [210 220 230 240 250]]


In [64]:
print(arr[:, ::2])

[[ 10  30  50]
 [ 60  80 100]
 [110 130 150]
 [160 180 200]
 [210 230 250]]


In [9]:
print(arr[:4, ::2])

[[ 10  30  50]
 [ 60  80 100]
 [110 130 150]
 [160 180 200]]


In [ ]:
# THREE DIMENSTION

In [10]:
arr = np.array([
 [
    [1, 2, 3], 
    [4, 5, 6]
 ], 
 [
    [7, 8, 9],
    [10, 11, 12]
 ]   
])
# array(layer_start : layer_stop,
        # row_start : array_stop,
        # column_start : column_stop
# )

print()

In [54]:
arr = np.array([
    [
        [1,  2,  3,  4,  5],
        [6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]
    ],

    [
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]
    ],

    [
        [41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]
    ],

    [
        [61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70],
        [71, 72, 73, 74, 75],
        [76, 77, 78, 79, 80]
    ]
])

# Q1 Extract the first 2 layers completely.

print(arr[0], "First", "\n")

# Q2 Extract the last 2 layers completely.

print(arr[-2], "Second", "\n")

# Q3 From every layer, extract the first 2 rows and last 3 columns.

print(arr[:, :2, 2:], "Third", "\n")

# Q4 From every layer, extract the last 2 rows and first 3 columns.

print(arr[:, -2:, :3], "Four", "\n")

# Q5 Extract alternate layers, starting from layer index 0.

print(arr[::2], "five", "\n")

# Q6 Extract alternate layers, starting from layer index 1.

print(arr[1::2], "Six", "\n")


# Q7 From every layer, extract alternate rows.

print(arr[:, ::2, :], "Seven", "\n")

# Q8 From every layer, extract alternate columns.

print(arr[:, :, ::2], "Eight", "\n")

# Q9 Extract alternate layers, alternate rows and alternate columns simultaneously.

print(arr[::2, ::2, ::2], "Nine", "\n")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] First 

[[41 42 43 44 45]
 [46 47 48 49 50]
 [51 52 53 54 55]
 [56 57 58 59 60]] Second 

[[[ 3  4  5]
  [ 8  9 10]]

 [[23 24 25]
  [28 29 30]]

 [[43 44 45]
  [48 49 50]]

 [[63 64 65]
  [68 69 70]]] Third 

[[[11 12 13]
  [16 17 18]]

 [[31 32 33]
  [36 37 38]]

 [[51 52 53]
  [56 57 58]]

 [[71 72 73]
  [76 77 78]]] Four 

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]] five 

[[[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[61 62 63 64 65]
  [66 67 68 69 70]
  [71 72 73 74 75]
  [76 77 78 79 80]]] Six 

[[[ 1  2  3  4  5]
  [11 12 13 14 15]]

 [[21 22 23 24 25]
  [31 32 33 34 35]]

 [[41 42 43 44 45]
  [51 52 53 54 55]]

 [[61 62 63 64 65]
  [71 72 73 74 75]]] Seven 

[[[ 1  3  5]
  [ 6  8 10]
  [11 13 15]
  [16 18 20]]

 [[21 23 25]
  [26 28 30]
  [31 33 35]
  [36 38 40]

In [55]:
# Q10 Reverse the order of layers, but keep rows and columns unchanged.

print(arr[::-1, :, :], "Ten", "\n")

[[[61 62 63 64 65]
  [66 67 68 69 70]
  [71 72 73 74 75]
  [76 77 78 79 80]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]] Ten 



In [60]:

# Q11 Keep the layers unchanged, but reverse every row horizontally.

print(arr[:, ::-1, :])

[[[16 17 18 19 20]
  [11 12 13 14 15]
  [ 6  7  8  9 10]
  [ 1  2  3  4  5]]

 [[36 37 38 39 40]
  [31 32 33 34 35]
  [26 27 28 29 30]
  [21 22 23 24 25]]

 [[56 57 58 59 60]
  [51 52 53 54 55]
  [46 47 48 49 50]
  [41 42 43 44 45]]

 [[76 77 78 79 80]
  [71 72 73 74 75]
  [66 67 68 69 70]
  [61 62 63 64 65]]]


In [64]:
# Q12 Keep the layers unchanged, but reverse the order of rows in every layer.

print(arr[:, :, ::-1])

[[[ 5  4  3  2  1]
  [10  9  8  7  6]
  [15 14 13 12 11]
  [20 19 18 17 16]]

 [[25 24 23 22 21]
  [30 29 28 27 26]
  [35 34 33 32 31]
  [40 39 38 37 36]]

 [[45 44 43 42 41]
  [50 49 48 47 46]
  [55 54 53 52 51]
  [60 59 58 57 56]]

 [[65 64 63 62 61]
  [70 69 68 67 66]
  [75 74 73 72 71]
  [80 79 78 77 76]]]


In [66]:
# Q13 Reverse: layers rows columns all simultaneously.

print(arr[::-1, ::-1, ::-1])

[[[80 79 78 77 76]
  [75 74 73 72 71]
  [70 69 68 67 66]
  [65 64 63 62 61]]

 [[60 59 58 57 56]
  [55 54 53 52 51]
  [50 49 48 47 46]
  [45 44 43 42 41]]

 [[40 39 38 37 36]
  [35 34 33 32 31]
  [30 29 28 27 26]
  [25 24 23 22 21]]

 [[20 19 18 17 16]
  [15 14 13 12 11]
  [10  9  8  7  6]
  [ 5  4  3  2  1]]]


In [69]:
# Q14 From the last 3 layers, extract the middle 2 rows and middle 3 columns.

print(arr[-3:, 1:3, 2])

[[28 33]
 [48 53]
 [68 73]]
