In [4]:
arr = np.array([
    [ 1,  2,  3,  4,  5,  6,  7,  8],
    [ 9, 10, 11, 12, 13, 14, 15, 16],
    [17, 18, 19, 20, 21, 22, 23, 24],
    [25, 26, 27, 28, 29, 30, 31, 32],
    [33, 34, 35, 36, 37, 38, 39, 40],
    [41, 42, 43, 44, 45, 46, 47, 48],
    [49, 50, 51, 52, 53, 54, 55, 56],
    [57, 58, 59, 60, 61, 62, 63, 64]
])

In [8]:
# Q13. Extract the first 5 rows and last 4 columns.

print(arr[:5, -4:])

[[ 5  6  7  8]
 [13 14 15 16]
 [21 22 23 24]
 [29 30 31 32]
 [37 38 39 40]]


In [13]:
# Q14. Extract the last 5 rows and first 3 columns.

print(arr[-5:, :3])

[[25 26 27]
 [33 34 35]
 [41 42 43]
 [49 50 51]
 [57 58 59]]


In [18]:
# Q15. Extract alternate rows and alternate columns, starting from index 1.

print(arr[1::2, ::2])

[[ 9 11 13 15]
 [25 27 29 31]
 [41 43 45 47]
 [57 59 61 63]]


In [21]:
# Q16. Extract alternate rows starting from index 0 and alternate columns starting from index 1.

print(arr[::2, 1::2])

[[ 2  4  6  8]
 [18 20 22 24]
 [34 36 38 40]
 [50 52 54 56]]


In [23]:
# Q17. Extract the middle 4 × 4 matrix.

print(arr[2:6, 2:6])

[[19 20 21 22]
 [27 28 29 30]
 [35 36 37 38]
 [43 44 45 46]]


In [53]:
# Q18. Extract the middle 4 rows but reverse the columns.

print(arr[2:6, ::-1])

[[24 23 22 21 20 19 18 17]
 [32 31 30 29 28 27 26 25]
 [40 39 38 37 36 35 34 33]
 [48 47 46 45 44 43 42 41]]


In [134]:
# Q19. Extract the last 6 rows in reverse order and first 5 columns in reverse order.
# pending

print(arr[-1:-7:-1, 4::-1])

[[61 60 59 58 57]
 [53 52 51 50 49]
 [45 44 43 42 41]
 [37 36 35 34 33]
 [29 28 27 26 25]
 [21 20 19 18 17]]


In [52]:
# Q20. Extract rows 1 to 6 using every second row and columns 0 to 7 using every second column.

print(arr[:7:2, :7:2])

[[ 1  3  5  7]
 [17 19 21 23]
 [33 35 37 39]
 [49 51 53 55]]


In [63]:
# Q21. Reverse the complete array using slicing only.

print(arr[::-1, ::-1])

[[64 63 62 61 60 59 58 57]
 [56 55 54 53 52 51 50 49]
 [48 47 46 45 44 43 42 41]
 [40 39 38 37 36 35 34 33]
 [32 31 30 29 28 27 26 25]
 [24 23 22 21 20 19 18 17]
 [16 15 14 13 12 11 10  9]
 [ 8  7  6  5  4  3  2  1]]


In [64]:
# Q22. Reverse only the rows while keeping the columns in their original order.

print(arr[::-1, :])

[[57 58 59 60 61 62 63 64]
 [49 50 51 52 53 54 55 56]
 [41 42 43 44 45 46 47 48]
 [33 34 35 36 37 38 39 40]
 [25 26 27 28 29 30 31 32]
 [17 18 19 20 21 22 23 24]
 [ 9 10 11 12 13 14 15 16]
 [ 1  2  3  4  5  6  7  8]]


In [66]:
# Q23. Keep the rows in their original order but reverse all columns.

print(arr[:, ::-1])

[[ 8  7  6  5  4  3  2  1]
 [16 15 14 13 12 11 10  9]
 [24 23 22 21 20 19 18 17]
 [32 31 30 29 28 27 26 25]
 [40 39 38 37 36 35 34 33]
 [48 47 46 45 44 43 42 41]
 [56 55 54 53 52 51 50 49]
 [64 63 62 61 60 59 58 57]]


In [108]:
# Q24. Extract the last 5 rows, reverse their order, and take every second column from right to left.

print(arr[-1:-6:-1, ::-2])

[[64 62 60 58]
 [56 54 52 50]
 [48 46 44 42]
 [40 38 36 34]
 [32 30 28 26]]


In [117]:
# Q25. Extract the first 6 rows in reverse order and every second column from left to right.

print(arr[5::-1, ::2])

[[41 43 45 47]
 [33 35 37 39]
 [25 27 29 31]
 [17 19 21 23]
 [ 9 11 13 15]
 [ 1  3  5  7]]


In [135]:
# Q26. Extract alternate rows from the bottom and alternate columns from the right.

print(arr[-1::-2, -1::-2])

[[64 62 60 58]
 [48 46 44 42]
 [32 30 28 26]
 [16 14 12 10]]


In [149]:
# Q27. Extract rows 6 to 2 in reverse order and columns 5 to 1 in reverse order.

print(arr[6:1:-1, 5:0:-1])

[[54 53 52 51 50]
 [46 45 44 43 42]
 [38 37 36 35 34]
 [30 29 28 27 26]
 [22 21 20 19 18]]


In [155]:
# Q28. Extract the first 7 rows, skip every alternate row, and reverse the selected columns.

print(arr[:7:2, ::-1])

[[ 8  7  6  5  4  3  2  1]
 [24 23 22 21 20 19 18 17]
 [40 39 38 37 36 35 34 33]
 [56 55 54 53 52 51 50 49]]


In [160]:
# Q29. Extract the last 6 rows, take every second row, and from each selected row take the middle 4 columns in reverse.

print(arr[-6::2, 5:1:-1])

[[22 21 20 19]
 [38 37 36 35]
 [54 53 52 51]]


In [165]:
# Q30. Extract a 3 × 4 section from the array such that:

# rows are selected from bottom to top
# columns are selected from right to left.

print(arr[-1:-4:-1, -1:-5:-1])

[[64 63 62 61]
 [56 55 54 53]
 [48 47 46 45]]


In [170]:
import numpy as np

arr = np.array([
    
    [
        [1, 2, 3, 4, 5, 6],
        [7, 8, 9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]
    ],

    
    [
        [31, 32, 33, 34, 35, 36],
        [37, 38, 39, 40, 41, 42],
        [43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59, 60]
    ],

    
    [
        [61, 62, 63, 64, 65, 66],
        [67, 68, 69, 70, 71, 72],
        [73, 74, 75, 76, 77, 78],
        [79, 80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89, 90]
    ],

    
    [
        [91, 92, 93, 94, 95, 96],
        [97, 98, 99, 100, 101, 102],
        [103, 104, 105, 106, 107, 108],
        [109, 110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119, 120]
    ]
])

In [174]:
# Q31. Extract the first 2 layers completely.

print(arr[2:])

[[[ 61  62  63  64  65  66]
  [ 67  68  69  70  71  72]
  [ 73  74  75  76  77  78]
  [ 79  80  81  82  83  84]
  [ 85  86  87  88  89  90]]

 [[ 91  92  93  94  95  96]
  [ 97  98  99 100 101 102]
  [103 104 105 106 107 108]
  [109 110 111 112 113 114]
  [115 116 117 118 119 120]]]


In [177]:
# Q32. Extract the last 2 layers completely in reverse order.

print(arr[-2:])

[[[ 61  62  63  64  65  66]
  [ 67  68  69  70  71  72]
  [ 73  74  75  76  77  78]
  [ 79  80  81  82  83  84]
  [ 85  86  87  88  89  90]]

 [[ 91  92  93  94  95  96]
  [ 97  98  99 100 101 102]
  [103 104 105 106 107 108]
  [109 110 111 112 113 114]
  [115 116 117 118 119 120]]]


In [182]:
# Q33. From every layer, extract the first 3 rows and last 3 columns.

print(arr[:, :3, -3:])

[[[  4   5   6]
  [ 10  11  12]
  [ 16  17  18]]

 [[ 34  35  36]
  [ 40  41  42]
  [ 46  47  48]]

 [[ 64  65  66]
  [ 70  71  72]
  [ 76  77  78]]

 [[ 94  95  96]
  [100 101 102]
  [106 107 108]]]


In [186]:
# Q34. From every layer, extract the last 3 rows and first 4 columns.

print(arr[:, -3:, :3])

[[[ 13  14  15]
  [ 19  20  21]
  [ 25  26  27]]

 [[ 43  44  45]
  [ 49  50  51]
  [ 55  56  57]]

 [[ 73  74  75]
  [ 79  80  81]
  [ 85  86  87]]

 [[103 104 105]
  [109 110 111]
  [115 116 117]]]


In [189]:
# Q35. Extract alternate layers starting from layer 0.

print(arr[::2, :, :])

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [13 14 15 16 17 18]
  [19 20 21 22 23 24]
  [25 26 27 28 29 30]]

 [[61 62 63 64 65 66]
  [67 68 69 70 71 72]
  [73 74 75 76 77 78]
  [79 80 81 82 83 84]
  [85 86 87 88 89 90]]]


In [193]:
# Q36. Extract alternate layers starting from layer 1.

print(arr[1::2, :, :])

[[[ 31  32  33  34  35  36]
  [ 37  38  39  40  41  42]
  [ 43  44  45  46  47  48]
  [ 49  50  51  52  53  54]
  [ 55  56  57  58  59  60]]

 [[ 91  92  93  94  95  96]
  [ 97  98  99 100 101 102]
  [103 104 105 106 107 108]
  [109 110 111 112 113 114]
  [115 116 117 118 119 120]]]


In [195]:
# Q37. From every layer, extract alternate rows and alternate columns.

print(arr[:, ::2, ::2])

[[[  1   3   5]
  [ 13  15  17]
  [ 25  27  29]]

 [[ 31  33  35]
  [ 43  45  47]
  [ 55  57  59]]

 [[ 61  63  65]
  [ 73  75  77]
  [ 85  87  89]]

 [[ 91  93  95]
  [103 105 107]
  [115 117 119]]]


In [197]:
# Q38. Extract alternate layers, alternate rows, and alternate columns simultaneously.

print(arr[::2, ::2, ::2])

[[[ 1  3  5]
  [13 15 17]
  [25 27 29]]

 [[61 63 65]
  [73 75 77]
  [85 87 89]]]


In [199]:
# Q39. Reverse the order of all layers while keeping rows and columns unchanged.

print(arr[::-1, :, :])

[[[ 91  92  93  94  95  96]
  [ 97  98  99 100 101 102]
  [103 104 105 106 107 108]
  [109 110 111 112 113 114]
  [115 116 117 118 119 120]]

 [[ 61  62  63  64  65  66]
  [ 67  68  69  70  71  72]
  [ 73  74  75  76  77  78]
  [ 79  80  81  82  83  84]
  [ 85  86  87  88  89  90]]

 [[ 31  32  33  34  35  36]
  [ 37  38  39  40  41  42]
  [ 43  44  45  46  47  48]
  [ 49  50  51  52  53  54]
  [ 55  56  57  58  59  60]]

 [[  1   2   3   4   5   6]
  [  7   8   9  10  11  12]
  [ 13  14  15  16  17  18]
  [ 19  20  21  22  23  24]
  [ 25  26  27  28  29  30]]]


In [201]:
# Q40. Keep layers unchanged, reverse all rows, and keep columns unchanged.

print(arr[:, ::-1, ::-1])

[[[ 30  29  28  27  26  25]
  [ 24  23  22  21  20  19]
  [ 18  17  16  15  14  13]
  [ 12  11  10   9   8   7]
  [  6   5   4   3   2   1]]

 [[ 60  59  58  57  56  55]
  [ 54  53  52  51  50  49]
  [ 48  47  46  45  44  43]
  [ 42  41  40  39  38  37]
  [ 36  35  34  33  32  31]]

 [[ 90  89  88  87  86  85]
  [ 84  83  82  81  80  79]
  [ 78  77  76  75  74  73]
  [ 72  71  70  69  68  67]
  [ 66  65  64  63  62  61]]

 [[120 119 118 117 116 115]
  [114 113 112 111 110 109]
  [108 107 106 105 104 103]
  [102 101 100  99  98  97]
  [ 96  95  94  93  92  91]]]


In [203]:
# Q41. Keep layers and rows unchanged, but reverse all columns.

print(arr[:, :, ::-1])

[[[  6   5   4   3   2   1]
  [ 12  11  10   9   8   7]
  [ 18  17  16  15  14  13]
  [ 24  23  22  21  20  19]
  [ 30  29  28  27  26  25]]

 [[ 36  35  34  33  32  31]
  [ 42  41  40  39  38  37]
  [ 48  47  46  45  44  43]
  [ 54  53  52  51  50  49]
  [ 60  59  58  57  56  55]]

 [[ 66  65  64  63  62  61]
  [ 72  71  70  69  68  67]
  [ 78  77  76  75  74  73]
  [ 84  83  82  81  80  79]
  [ 90  89  88  87  86  85]]

 [[ 96  95  94  93  92  91]
  [102 101 100  99  98  97]
  [108 107 106 105 104 103]
  [114 113 112 111 110 109]
  [120 119 118 117 116 115]]]


In [205]:
# Q42. Reverse layers, rows, and columns simultaneously.

print(arr[::-1, ::-1, ::-1])

[[[120 119 118 117 116 115]
  [114 113 112 111 110 109]
  [108 107 106 105 104 103]
  [102 101 100  99  98  97]
  [ 96  95  94  93  92  91]]

 [[ 90  89  88  87  86  85]
  [ 84  83  82  81  80  79]
  [ 78  77  76  75  74  73]
  [ 72  71  70  69  68  67]
  [ 66  65  64  63  62  61]]

 [[ 60  59  58  57  56  55]
  [ 54  53  52  51  50  49]
  [ 48  47  46  45  44  43]
  [ 42  41  40  39  38  37]
  [ 36  35  34  33  32  31]]

 [[ 30  29  28  27  26  25]
  [ 24  23  22  21  20  19]
  [ 18  17  16  15  14  13]
  [ 12  11  10   9   8   7]
  [  6   5   4   3   2   1]]]


In [211]:
# Q43. Extract the last 3 layers, middle 3 rows, and middle 4 columns.

print(arr[-3:, 1:4, 0:4])

[[[ 37  38  39  40]
  [ 43  44  45  46]
  [ 49  50  51  52]]

 [[ 67  68  69  70]
  [ 73  74  75  76]
  [ 79  80  81  82]]

 [[ 97  98  99 100]
  [103 104 105 106]
  [109 110 111 112]]]


In [220]:
# Q44. Extract the first 3 layers in reverse order and first 4 rows in reverse order.

print(arr[2::-1, 3::-1, : ])

[[[79 80 81 82 83 84]
  [73 74 75 76 77 78]
  [67 68 69 70 71 72]
  [61 62 63 64 65 66]]

 [[49 50 51 52 53 54]
  [43 44 45 46 47 48]
  [37 38 39 40 41 42]
  [31 32 33 34 35 36]]

 [[19 20 21 22 23 24]
  [13 14 15 16 17 18]
  [ 7  8  9 10 11 12]
  [ 1  2  3  4  5  6]]]


In [226]:
# Q45. Extract the last 3 layers in reverse order and last 4 columns in reverse order.

print(arr[-1:-4:-1, :, -1:-5:-1])

[[[ 96  95  94  93]
  [102 101 100  99]
  [108 107 106 105]
  [114 113 112 111]
  [120 119 118 117]]

 [[ 66  65  64  63]
  [ 72  71  70  69]
  [ 78  77  76  75]
  [ 84  83  82  81]
  [ 90  89  88  87]]

 [[ 36  35  34  33]
  [ 42  41  40  39]
  [ 48  47  46  45]
  [ 54  53  52  51]
  [ 60  59  58  57]]]


In [238]:
# Q46. From every layer:

# take alternate rows from bottom to top
# take alternate columns from right to left.

print(arr[:, -1::-2, -1::-2])

[[[ 30  28  26]
  [ 18  16  14]
  [  6   4   2]]

 [[ 60  58  56]
  [ 48  46  44]
  [ 36  34  32]]

 [[ 90  88  86]
  [ 78  76  74]
  [ 66  64  62]]

 [[120 118 116]
  [108 106 104]
  [ 96  94  92]]]


In [243]:
# Q47. Extract alternate layers from the end, reverse the rows, and take every second column.

print(arr[::2, ::-1, ::2])

[[[25 27 29]
  [19 21 23]
  [13 15 17]
  [ 7  9 11]
  [ 1  3  5]]

 [[85 87 89]
  [79 81 83]
  [73 75 77]
  [67 69 71]
  [61 63 65]]]


In [258]:
# Q48. Extract:

# layers from 3 to 1 in reverse
# rows from 4 to 1 in reverse
# columns from 5 to 0 in reverse.

print(arr[-2::-1, 3::-1, 4::-1])

[[[83 82 81 80 79]
  [77 76 75 74 73]
  [71 70 69 68 67]
  [65 64 63 62 61]]

 [[53 52 51 50 49]
  [47 46 45 44 43]
  [41 40 39 38 37]
  [35 34 33 32 31]]

 [[23 22 21 20 19]
  [17 16 15 14 13]
  [11 10  9  8  7]
  [ 5  4  3  2  1]]]


In [260]:
# Q49. Extract the middle 2 layers, reverse their rows, and take alternate columns.

print(arr[1:3, ::-1, ::2])

[[[55 57 59]
  [49 51 53]
  [43 45 47]
  [37 39 41]
  [31 33 35]]

 [[85 87 89]
  [79 81 83]
  [73 75 77]
  [67 69 71]
  [61 63 65]]]


In [261]:
# Q50. Extract the last 3 layers, take every second row from bottom to top, and every second column from right to left.

print(arr[-3:, ::-2, ::-2])

[[[ 60  58  56]
  [ 48  46  44]
  [ 36  34  32]]

 [[ 90  88  86]
  [ 78  76  74]
  [ 66  64  62]]

 [[120 118 116]
  [108 106 104]
  [ 96  94  92]]]
