In [3]:
import numpy as np

1. A company wants to generate data for 72 employees. 
• Employee IDs should start from 1001. 
• Employee performance scores should range equally from 35 to 95. 
• Arrange the data into 6 departments with 12 employees each. 
• Extract the last 3 employees from the first 3 departments. 
• Create a separate independent array from the extracted data. 
• Change one value in the new array to 999. 
• Verify whether the original data changed.

In [31]:
emp_id = np.arange(1001, 1001+72)
print("Emplyees Id =", emp_id, "\n")

perf_scores = np.linspace(35, 95, 72)
print("Performance scores =", perf_scores, "\n")

depart_id= emp_id.reshape(6, 12)
depart_scores = perf_scores.reshape(6, 12)
print("Department ID = ", depart_id, "\n")
print("Department scores = ", depart_scores, "\n")

print("Original Performance Scores Shape:", depart_scores.shape, "\n")

extrac_data = depart_scores[:3, 9:]
print("Extracted Data", extrac_data, "\n")

indep_array = extrac_data.copy()
print(indep_array, "\n")

indep_array[0, 0] = 999
print("Modify Independent Array = ", indep_array, "\n")

print("Original Data", depart_scores[0, 9], "\n")
print("Changes Data", depart_scores[0, 9] == 999)

Emplyees Id = [1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014
 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028
 1029 1030 1031 1032 1033 1034 1035 1036 1037 1038 1039 1040 1041 1042
 1043 1044 1045 1046 1047 1048 1049 1050 1051 1052 1053 1054 1055 1056
 1057 1058 1059 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069 1070
 1071 1072] 

Performance scores = [35.         35.84507042 36.69014085 37.53521127 38.38028169 39.22535211
 40.07042254 40.91549296 41.76056338 42.6056338  43.45070423 44.29577465
 45.14084507 45.98591549 46.83098592 47.67605634 48.52112676 49.36619718
 50.21126761 51.05633803 51.90140845 52.74647887 53.5915493  54.43661972
 55.28169014 56.12676056 56.97183099 57.81690141 58.66197183 59.50704225
 60.35211268 61.1971831  62.04225352 62.88732394 63.73239437 64.57746479
 65.42253521 66.26760563 67.11267606 67.95774648 68.8028169  69.64788732
 70.49295775 71.33802817 72.18309859 73.02816901 73.87323944 74.71830986
 75.56338028

2. Create an array containing numbers from 1 to 120 and arrange it into 4 × 5 × 6.
   From this array, extract:
   • Layers 4 and 2
   • Rows 5, 3 and 1
   • Columns 6, 4 and 2
Then determine whether the extracted array shares memory with the original array.

In [75]:
num = np.arange(1, 121).reshape(4, 5, 6)
print("*",num, "\n")

extracted = num[3:0:-2, 4::-2, 5:0:-2]
print(extracted, "\n")

print("Share memory with the array =", np.shares_memory(num, extracted))

* [[[  1   2   3   4   5   6]
  [  7   8   9  10  11  12]
  [ 13  14  15  16  17  18]
  [ 19  20  21  22  23  24]
  [ 25  26  27  28  29  30]]

 [[ 31  32  33  34  35  36]
  [ 37  38  39  40  41  42]
  [ 43  44  45  46  47  48]
  [ 49  50  51  52  53  54]
  [ 55  56  57  58  59  60]]

 [[ 61  62  63  64  65  66]
  [ 67  68  69  70  71  72]
  [ 73  74  75  76  77  78]
  [ 79  80  81  82  83  84]
  [ 85  86  87  88  89  90]]

 [[ 91  92  93  94  95  96]
  [ 97  98  99 100 101 102]
  [103 104 105 106 107 108]
  [109 110 111 112 113 114]
  [115 116 117 118 119 120]]] 

[[[120 118 116]
  [108 106 104]
  [ 96  94  92]]

 [[ 60  58  56]
  [ 48  46  44]
  [ 36  34  32]]] 

Share memory with the array = True


3. A temperature monitoring system records 96 readings.
Generate reading numbers starting from 1 and temperatures equally spaced between 18°C and 42°C.

Arrange the data into 4 days × 4 time periods × 6 readings.

Extract days 2 and 4, time periods 1 and 3, and alternate readings. 
Store the result separately and modify one value. Check the effect on the original.

In [93]:
temp_nums = np.arange(1, 97)
print(temp_nums, "\n")

temp = np.linspace(18, 42, 96)
print(temp, "\n")

temp_arange = temp.reshape(4, 4, 6)
print(temp_arange, "\n")

extrac_temp = temp_arange[1:4:2, 0:3:2, ::2]
print(extrac_temp, "\n")

sepect = extrac_temp.copy()
sepect[0, 0, 0] = 999.0

print("Modify seprate array \n", sepect, "\n")

print("\nOriginal Data at corresponding position:", temp_arange[1, 0, 0])
print("Did the original data change?", temp_arange[1, 0, 0] == 999.0)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96] 

[18.         18.25263158 18.50526316 18.75789474 19.01052632 19.26315789
 19.51578947 19.76842105 20.02105263 20.27368421 20.52631579 20.77894737
 21.03157895 21.28421053 21.53684211 21.78947368 22.04210526 22.29473684
 22.54736842 22.8        23.05263158 23.30526316 23.55789474 23.81052632
 24.06315789 24.31578947 24.56842105 24.82105263 25.07368421 25.32631579
 25.57894737 25.83157895 26.08421053 26.33684211 26.58947368 26.84210526
 27.09473684 27.34736842 27.6        27.85263158 28.10526316 28.35789474
 28.61052632 28.86315789 29.11578947 29.36842105 29.62105263 29.87368421
 30.12631579 30.37894737 30.63157895 30.88421053 31.13684211 31.38947368
 31.64210526 31.89473684 32.14736842 32.4       

4. Generate 60 values equally spaced between 10 and 100.

Arrange them into 5 × 4 × 3. 
Extract the last 3 rows of the first layer, the first 2 columns, and every alternate value. 
Then create both a view and a copy of the extracted data and compare their behavior after modification.

In [101]:
values = np.linspace(10, 100, 60)
print(values, "\n")

arr = values.reshape(5, 4, 3)
print("Array shape\n", arr, "\n")

extract = arr[0, 1:4, :2:2]
print(extract, "\n")

extracted_view = extract.view()
extracted_copy = extract.copy()

extracted_view[0, 0] = 999.0

print("\n--- After modifying the VIEW ---")
print("Did the original array change?", arr[0, 1, 0] == 999.0)
print("Does the view share memory with original?", np.shares_memory(arr, extracted_view))

extracted_copy[0, 0] = 888.0

print("\n--- After modifying the COPY ---")
print("Original array value at that position (should be unaffected by copy):", arr[0, 1, 0])
print("Does the copy share memory with original?", np.shares_memory(arr, extracted_copy))

[ 10.          11.52542373  13.05084746  14.57627119  16.10169492
  17.62711864  19.15254237  20.6779661   22.20338983  23.72881356
  25.25423729  26.77966102  28.30508475  29.83050847  31.3559322
  32.88135593  34.40677966  35.93220339  37.45762712  38.98305085
  40.50847458  42.03389831  43.55932203  45.08474576  46.61016949
  48.13559322  49.66101695  51.18644068  52.71186441  54.23728814
  55.76271186  57.28813559  58.81355932  60.33898305  61.86440678
  63.38983051  64.91525424  66.44067797  67.96610169  69.49152542
  71.01694915  72.54237288  74.06779661  75.59322034  77.11864407
  78.6440678   80.16949153  81.69491525  83.22033898  84.74576271
  86.27118644  87.79661017  89.3220339   90.84745763  92.37288136
  93.89830508  95.42372881  96.94915254  98.47457627 100.        ] 

Array shape
 [[[ 10.          11.52542373  13.05084746]
  [ 14.57627119  16.10169492  17.62711864]
  [ 19.15254237  20.6779661   22.20338983]
  [ 23.72881356  25.25423729  26.77966102]]

 [[ 28.30508475  29

5. A school has 3 classes, 5 subjects and 8 students.
Generate student IDs starting from 101 and marks equally spaced between 30 and 100. Arrange both into the required 3D structure.
Extract the marks of Class 2, Subjects 1, 3 and 5, and Students 2, 4, 6 and 8. Create a copy of this result and modify it.

In [114]:
total_elements = 3 * 5 * 8

student_ids = np.arange(101, 101 + total_elements)
marks = np.linspace(30, 100, total_elements)

print("Students id: \n", student_ids, "\n")
print("Marks of students: \n", marks, "\n")

student_ids_3d = student_ids.reshape(3, 5, 8)
marks_3d = marks.reshape(3, 5, 8)

print("Original Students 3D Shape: \n", student_ids_3d, "\n")
print("Original Marks 3D Shape: \n", marks_3d, "\n")

extracted_marks = marks_3d[2, ::2, 1::2]

print("\nExtracted Marks Shape:", extracted_marks.shape)
print("Extracted Marks:\n", extracted_marks)

marks_copy = extracted_marks.copy()

marks_copy[0, 0] = 999.0

print("\nModified Copy:\n", marks_copy)

print("\nOriginal Marks value at corresponding position [1, 0, 1]:", marks_3d[1, 0, 1])
print("Did the original marks change?", marks_3d[1, 0, 1] == 999.0)

Students id: 
 [101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136
 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154
 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172
 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190
 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208
 209 210 211 212 213 214 215 216 217 218 219 220] 

Marks of students: 
 [ 30.          30.58823529  31.17647059  31.76470588  32.35294118
  32.94117647  33.52941176  34.11764706  34.70588235  35.29411765
  35.88235294  36.47058824  37.05882353  37.64705882  38.23529412
  38.82352941  39.41176471  40.          40.58823529  41.17647059
  41.76470588  42.35294118  42.94117647  43.52941176  44.11764706
  44.70588235  45.29411765  45.88235294  46.47058824  47.05882353
  47.64705882  48.23529412  48.82352941  49.41176471  50.
  50.58823529  51.17

6. Create an array using np.arange(10, 201, 10). Determine its size and reshape it into a suitable 2D structure. Then reverse the rows, select every alternate column, extract the resulting section, create a view, modify one element, and check whether the original array changed.

In [118]:
arr = np.arange(10, 201, 10)
print("Size of the array:", arr.size)

arr_2d = arr.reshape(4, 5)
print("\nOriginal 2D Array:\n", arr_2d)

extracted = arr_2d[::-1, ::2]
print("\nExtracted Section:\n", extracted)

extracted_view = extracted.view()

extracted_view[0, 0] = 999

print("\nModified View:\n", extracted_view)

print("\nOriginal 2D Array after modification:\n", arr_2d)
print("Did the original array change?", arr_2d[-1, 0] == 999)

Size of the array: 20

Original 2D Array:
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]

Extracted Section:
 [[160 180 200]
 [110 130 150]
 [ 60  80 100]
 [ 10  30  50]]

Modified View:
 [[999 180 200]
 [110 130 150]
 [ 60  80 100]
 [ 10  30  50]]

Original 2D Array after modification:
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [999 170 180 190 200]]
Did the original array change? True


7. Generate 100 equally spaced values between -50 and 50. Arrange them into a 10 × 10 matrix. Extract the middle 6 rows and middle 6 columns. Then create a copy of this extracted matrix and change its top-left value to 500. Check the original matrix.

In [123]:
values = np.linspace(-50, 50, 100)

matrix_10x10 = values.reshape(10, 10)
print("Original 10x10 Matrix Shape: \n", matrix_10x10)

middle_extracted = matrix_10x10[2:8, 2:8]
print("\nExtracted Middle Matrix Shape: \n", middle_extracted)

matrix_copy = middle_extracted.copy()

matrix_copy[0, 0] = 500
print("\nModified Copy (Top-Left changed to 500):\n", matrix_copy)

print("\nOriginal Matrix value at [2, 2]:", matrix_10x10[2, 2])
print("Did the original matrix change?", matrix_10x10[2, 2] == 500)

Original 10x10 Matrix Shape: 
 [[-50.         -48.98989899 -47.97979798 -46.96969697 -45.95959596
  -44.94949495 -43.93939394 -42.92929293 -41.91919192 -40.90909091]
 [-39.8989899  -38.88888889 -37.87878788 -36.86868687 -35.85858586
  -34.84848485 -33.83838384 -32.82828283 -31.81818182 -30.80808081]
 [-29.7979798  -28.78787879 -27.77777778 -26.76767677 -25.75757576
  -24.74747475 -23.73737374 -22.72727273 -21.71717172 -20.70707071]
 [-19.6969697  -18.68686869 -17.67676768 -16.66666667 -15.65656566
  -14.64646465 -13.63636364 -12.62626263 -11.61616162 -10.60606061]
 [ -9.5959596   -8.58585859  -7.57575758  -6.56565657  -5.55555556
   -4.54545455  -3.53535354  -2.52525253  -1.51515152  -0.50505051]
 [  0.50505051   1.51515152   2.52525253   3.53535354   4.54545455
    5.55555556   6.56565657   7.57575758   8.58585859   9.5959596 ]
 [ 10.60606061  11.61616162  12.62626263  13.63636364  14.64646465
   15.65656566  16.66666667  17.67676768  18.68686869  19.6969697 ]
 [ 20.70707071  21.71717

8. A company has 120 products. Generate product IDs starting from 5001 and product prices equally spaced between 500 and 50,000. Arrange the data into 4 regions × 5 categories × 6 products. Extract Regions 1 and 3, Categories 2 and 4, and Products 1, 3 and 5. Then create a view and a copy of the extracted prices.

In [128]:
product_ids = np.arange(5001, 5001 + 120)

prices = np.linspace(500, 50000, 120)

product_ids_3d = product_ids.reshape(4, 5, 6)
print("Arange the Products: \n", product_ids_3d, "\n")
prices_3d = prices.reshape(4, 5, 6)
print("Original Prices 3D Shape: \n", prices_3d, "\n")

extracted_prices = prices_3d[0:3:2, 1:4:2, ::2]

print("\nExtracted Prices Shape:", extracted_prices)
print("Extracted Prices:\n", extracted_prices)

prices_view = extracted_prices.view()
prices_copy = extracted_prices.copy()

print("\nDoes the view share memory with the original? ", np.shares_memory(prices_3d, prices_view))
print("Does the copy share memory with the original? ", np.shares_memory(prices_3d, prices_copy))

Arange the Products: 
 [[[5001 5002 5003 5004 5005 5006]
  [5007 5008 5009 5010 5011 5012]
  [5013 5014 5015 5016 5017 5018]
  [5019 5020 5021 5022 5023 5024]
  [5025 5026 5027 5028 5029 5030]]

 [[5031 5032 5033 5034 5035 5036]
  [5037 5038 5039 5040 5041 5042]
  [5043 5044 5045 5046 5047 5048]
  [5049 5050 5051 5052 5053 5054]
  [5055 5056 5057 5058 5059 5060]]

 [[5061 5062 5063 5064 5065 5066]
  [5067 5068 5069 5070 5071 5072]
  [5073 5074 5075 5076 5077 5078]
  [5079 5080 5081 5082 5083 5084]
  [5085 5086 5087 5088 5089 5090]]

 [[5091 5092 5093 5094 5095 5096]
  [5097 5098 5099 5100 5101 5102]
  [5103 5104 5105 5106 5107 5108]
  [5109 5110 5111 5112 5113 5114]
  [5115 5116 5117 5118 5119 5120]]] 

Original Prices 3D Shape: 
 [[[  500.           915.96638655  1331.93277311  1747.89915966
    2163.86554622  2579.83193277]
  [ 2995.79831933  3411.76470588  3827.73109244  4243.69747899
    4659.66386555  5075.6302521 ]
  [ 5491.59663866  5907.56302521  6323.52941176  6739.49579832
  

9. Create np.arange(1, 181) and reshape it into 5 × 6 × 6. Without using loops, extract the last 2 layers, rows in reverse order, and every second column starting from the last column. Then determine the shape of the resulting array.

In [132]:
arr = np.arange(1, 181).reshape(5, 6, 6)
print("Original Array Shape: \n", arr, "\n")

extracted = arr[3:, ::-1, 5::-2]

print("Extracted Shape:", extracted.shape)
print("\nExtracted Array:\n", extracted)

Original Array Shape: 
 [[[  1   2   3   4   5   6]
  [  7   8   9  10  11  12]
  [ 13  14  15  16  17  18]
  [ 19  20  21  22  23  24]
  [ 25  26  27  28  29  30]
  [ 31  32  33  34  35  36]]

 [[ 37  38  39  40  41  42]
  [ 43  44  45  46  47  48]
  [ 49  50  51  52  53  54]
  [ 55  56  57  58  59  60]
  [ 61  62  63  64  65  66]
  [ 67  68  69  70  71  72]]

 [[ 73  74  75  76  77  78]
  [ 79  80  81  82  83  84]
  [ 85  86  87  88  89  90]
  [ 91  92  93  94  95  96]
  [ 97  98  99 100 101 102]
  [103 104 105 106 107 108]]

 [[109 110 111 112 113 114]
  [115 116 117 118 119 120]
  [121 122 123 124 125 126]
  [127 128 129 130 131 132]
  [133 134 135 136 137 138]
  [139 140 141 142 143 144]]

 [[145 146 147 148 149 150]
  [151 152 153 154 155 156]
  [157 158 159 160 161 162]
  [163 164 165 166 167 168]
  [169 170 171 172 173 174]
  [175 176 177 178 179 180]]] 

Extracted Shape: (2, 6, 3)

Extracted Array:
 [[[144 142 140]
  [138 136 134]
  [132 130 128]
  [126 124 122]
  [120 118 116

10. Generate 48 equally spaced values between 100 and 500. Reshape them into 4 × 4 × 3. Extract Layers 4 and 2, Rows 4 and 2, and Columns 3 and 1. Create a copy of the result. Modify the copy and prove that the original array is unaffected.

In [135]:
values = np.linspace(100, 500, 48)

arr_3d = values.reshape(4, 4, 3)
print("Original Array Shape: \n", arr_3d, "\n")

extracted = arr_3d[3:0:-2, 3:0:-2, 2::-2]

print("\nExtracted Shape:", extracted.shape)
print("Extracted Data:\n", extracted)

extracted_copy = extracted.copy()

extracted_copy[0, 0, 0] = 999.0
print("\nModified Copy:\n", extracted_copy)

print("\nOriginal Array value at corresponding position [3, 3, 2]:", arr_3d[3, 3, 2])
print("Did the original array change?", arr_3d[3, 3, 2] == 999.0)
print("Does the copy share memory with the original?", np.shares_memory(arr_3d, extracted_copy))

Original Array Shape: 
 [[[100.         108.5106383  117.0212766 ]
  [125.53191489 134.04255319 142.55319149]
  [151.06382979 159.57446809 168.08510638]
  [176.59574468 185.10638298 193.61702128]]

 [[202.12765957 210.63829787 219.14893617]
  [227.65957447 236.17021277 244.68085106]
  [253.19148936 261.70212766 270.21276596]
  [278.72340426 287.23404255 295.74468085]]

 [[304.25531915 312.76595745 321.27659574]
  [329.78723404 338.29787234 346.80851064]
  [355.31914894 363.82978723 372.34042553]
  [380.85106383 389.36170213 397.87234043]]

 [[406.38297872 414.89361702 423.40425532]
  [431.91489362 440.42553191 448.93617021]
  [457.44680851 465.95744681 474.46808511]
  [482.9787234  491.4893617  500.        ]]] 


Extracted Shape: (2, 2, 2)
Extracted Data:
 [[[500.         482.9787234 ]
  [448.93617021 431.91489362]]

 [[295.74468085 278.72340426]
  [244.68085106 227.65957447]]]

Modified Copy:
 [[[999.         482.9787234 ]
  [448.93617021 431.91489362]]

 [[295.74468085 278.72340426]


11. A fitness tracker records data for 7 days, 4 time periods per day and 5 readings per period. Generate reading IDs using arange() and calorie values using linspace() from 100 to 500. Create the required 3D arrays. Extract Days 2–6, alternate time periods, and the last 3 readings. Create a view of the result and modify one value.

In [136]:
total_elements = 7 * 4 * 5

reading_ids = np.arange(1, total_elements + 1)
calories = np.linspace(100, 500, total_elements)

reading_ids_3d = reading_ids.reshape(7, 4, 5)
calories_3d = calories.reshape(7, 4, 5)

print("Original Calories 3D Shape:", calories_3d.shape)

extracted_calories = calories_3d[1:6, ::2, -3:]

print("\nExtracted Calories Shape:", extracted_calories.shape)
print("Extracted Calories:\n", extracted_calories)

calories_view = extracted_calories.view()

calories_view[0, 0, 0] = 999.0

print("\nModified View:\n", calories_view)

print("\nOriginal Calories value at corresponding position [1, 0, 2]:", calories_3d[1, 0, 2])
print("Did the original array change?", calories_3d[1, 0, 2] == 999.0)
print("Does the view share memory with the original?", np.shares_memory(calories_3d, calories_view))

Original Calories 3D Shape: (7, 4, 5)

Extracted Calories Shape: (5, 2, 3)
Extracted Calories:
 [[[163.30935252 166.18705036 169.0647482 ]
  [192.08633094 194.96402878 197.84172662]]

 [[220.86330935 223.74100719 226.61870504]
  [249.64028777 252.51798561 255.39568345]]

 [[278.41726619 281.29496403 284.17266187]
  [307.1942446  310.07194245 312.94964029]]

 [[335.97122302 338.84892086 341.72661871]
  [364.74820144 367.62589928 370.50359712]]

 [[393.52517986 396.4028777  399.28057554]
  [422.30215827 425.17985612 428.05755396]]]

Modified View:
 [[[999.         166.18705036 169.0647482 ]
  [192.08633094 194.96402878 197.84172662]]

 [[220.86330935 223.74100719 226.61870504]
  [249.64028777 252.51798561 255.39568345]]

 [[278.41726619 281.29496403 284.17266187]
  [307.1942446  310.07194245 312.94964029]]

 [[335.97122302 338.84892086 341.72661871]
  [364.74820144 367.62589928 370.50359712]]

 [[393.52517986 396.4028777  399.28057554]
  [422.30215827 425.17985612 428.05755396]]]

Origin

12. Generate the sequence 100, 95, 90, 85, ..., 5 using arange(). Reshape it into a suitable 2D array. Then reverse the rows, select alternate columns, extract the resulting section, create a copy, modify the copy, and compare it with the original.

In [137]:
seq = np.arange(100, 4, -5)
print("Sequence Size:", seq.size)

arr_2d = seq.reshape(4, 5)
print("\nOriginal 2D Array:\n", arr_2d)

extracted = arr_2d[::-1, ::2]
print("\nExtracted Section:\n", extracted)

extracted_copy = extracted.copy()

extracted_copy[0, 0] = 999
print("\nModified Copy:\n", extracted_copy)

print("\nOriginal 2D Array after modification:\n", arr_2d)
print("Did the original array change?", arr_2d[-1, 0] == 999)
print("Does the copy share memory with the original?", np.shares_memory(arr_2d, extracted_copy))

Sequence Size: 20

Original 2D Array:
 [[100  95  90  85  80]
 [ 75  70  65  60  55]
 [ 50  45  40  35  30]
 [ 25  20  15  10   5]]

Extracted Section:
 [[ 25  15   5]
 [ 50  40  30]
 [ 75  65  55]
 [100  90  80]]

Modified Copy:
 [[999  15   5]
 [ 50  40  30]
 [ 75  65  55]
 [100  90  80]]

Original 2D Array after modification:
 [[100  95  90  85  80]
 [ 75  70  65  60  55]
 [ 50  45  40  35  30]
 [ 25  20  15  10   5]]
Did the original array change? False
Does the copy share memory with the original? False


13. A bank has 90 transaction records. Generate Transaction IDs starting from 10001 and transaction amounts equally spaced between 1,000 and 90,000. Arrange them into 3 branches × 5 days × 6 transactions. Extract Branches 1 and 3, Days 2, 4 and 5, and Transactions 1, 3 and 5.

In [138]:
total_elements = 90

transaction_ids = np.arange(10001, 10001 + total_elements)

amounts = np.linspace(1000, 90000, total_elements)

ids_3d = transaction_ids.reshape(3, 5, 6)
amounts_3d = amounts.reshape(3, 5, 6)

print("Original Amounts Shape:", amounts_3d.shape)

extracted_amounts = amounts_3d[0:3:2, [1, 3, 4], ::2]

print("\nExtracted Amounts Shape:", extracted_amounts.shape)
print("Extracted Amounts:\n", extracted_amounts)

Original Amounts Shape: (3, 5, 6)

Extracted Amounts Shape: (2, 3, 3)
Extracted Amounts:
 [[[ 7000.  9000. 11000.]
  [19000. 21000. 23000.]
  [25000. 27000. 29000.]]

 [[67000. 69000. 71000.]
  [79000. 81000. 83000.]
  [85000. 87000. 89000.]]]


14. Create np.arange(1, 97).reshape(4, 4, 6). Extract exactly 2 layers, 3 rows and 4 columns. The selected layers must be the first and third, the rows must be the last three rows, and the columns must be alternate columns. Then determine whether the result is a view or copy.

In [141]:
arr = np.arange(1, 97).reshape(4, 4, 6)
print("Original Array Shape:", arr)

extracted = arr[[0, 2], 1:, ::2]

print("\nExtracted Shape:", extracted)
print("Extracted Data:\n", extracted)

shares_mem = np.shares_memory(arr, extracted)
print("\nDoes it share memory with the original?", shares_mem)

if shares_mem:
    print("The result is a VIEW.")
else:
    print("The result is a COPY.")

Original Array Shape: [[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]
  [37 38 39 40 41 42]
  [43 44 45 46 47 48]]

 [[49 50 51 52 53 54]
  [55 56 57 58 59 60]
  [61 62 63 64 65 66]
  [67 68 69 70 71 72]]

 [[73 74 75 76 77 78]
  [79 80 81 82 83 84]
  [85 86 87 88 89 90]
  [91 92 93 94 95 96]]]

Extracted Shape: [[[ 7  9 11]
  [13 15 17]
  [19 21 23]]

 [[55 57 59]
  [61 63 65]
  [67 69 71]]]
Extracted Data:
 [[[ 7  9 11]
  [13 15 17]
  [19 21 23]]

 [[55 57 59]
  [61 63 65]
  [67 69 71]]]

Does it share memory with the original? False
The result is a COPY.


15. Generate 64 equally spaced values between 0 and 1. Reshape them into 8 × 8. Extract rows 2 through 7, columns 1 through 6, and every alternate column. Create a copy of this extracted array. Modify both the extracted array and the copy. Observe the effect on the original.

In [142]:
values = np.linspace(0, 1, 64)
arr_8x8 = values.reshape(8, 8)
print("Original 8x8 Array Shape:", arr_8x8)

extracted = arr_8x8[1:8, 0:7:2]
print("\nExtracted Array Shape:", extracted)
print("Extracted Array:\n", extracted)

extracted_copy = extracted.copy()

extracted[0, 0] = 999.0     
extracted_copy[0, 0] = 888.0  

print("\nOriginal Array after modifications:\n", arr_8x8)
print("\nDid the original array change due to the extracted array (view)?", arr_8x8[1, 0] == 999.0)
print("Did the original array change due to the copy?", arr_8x8[1, 0] == 888.0)

Original 8x8 Array Shape: [[0.         0.01587302 0.03174603 0.04761905 0.06349206 0.07936508
  0.0952381  0.11111111]
 [0.12698413 0.14285714 0.15873016 0.17460317 0.19047619 0.20634921
  0.22222222 0.23809524]
 [0.25396825 0.26984127 0.28571429 0.3015873  0.31746032 0.33333333
  0.34920635 0.36507937]
 [0.38095238 0.3968254  0.41269841 0.42857143 0.44444444 0.46031746
  0.47619048 0.49206349]
 [0.50793651 0.52380952 0.53968254 0.55555556 0.57142857 0.58730159
  0.6031746  0.61904762]
 [0.63492063 0.65079365 0.66666667 0.68253968 0.6984127  0.71428571
  0.73015873 0.74603175]
 [0.76190476 0.77777778 0.79365079 0.80952381 0.82539683 0.84126984
  0.85714286 0.87301587]
 [0.88888889 0.9047619  0.92063492 0.93650794 0.95238095 0.96825397
  0.98412698 1.        ]]

Extracted Array Shape: [[0.12698413 0.15873016 0.19047619 0.22222222]
 [0.25396825 0.28571429 0.31746032 0.34920635]
 [0.38095238 0.41269841 0.44444444 0.47619048]
 [0.50793651 0.53968254 0.57142857 0.6031746 ]
 [0.63492063 0.66

16. A university stores data for 4 departments, 3 semesters and 5 subjects. Generate subject IDs using arange() and marks using linspace(). Arrange them into the required 3D structure. Extract Departments 2 and 4, Semesters 1 and 3, and Subjects 2, 3 and 5. Create a copy of the marks and change one mark to 0. Verify the original marks.

In [162]:
arr = np.arange(1, 241).reshape(4, 5, 12)
print("Original Array Shape:", arr, "\n")

extracted = arr[3::-1, :4, 11:0:-2]
print("Extracted Shape:", extracted)

A = extracted
B = A.copy()
C = A.view()

B[0, 0, 0] = 999
C[0, 0, 1] = 888

print("\n--- Memory & Impact Verification ---")
print("Does B (copy) share memory with A?", np.shares_memory(A, B))
print("Does C (view) share memory with A?", np.shares_memory(A, C))
print("Does C share memory with the original array 'arr'?", np.shares_memory(arr, C))
print("Did the original array 'arr' change?", arr[-1, 0, 10] == 888)

Original Array Shape: [[[  1   2   3   4   5   6   7   8   9  10  11  12]
  [ 13  14  15  16  17  18  19  20  21  22  23  24]
  [ 25  26  27  28  29  30  31  32  33  34  35  36]
  [ 37  38  39  40  41  42  43  44  45  46  47  48]
  [ 49  50  51  52  53  54  55  56  57  58  59  60]]

 [[ 61  62  63  64  65  66  67  68  69  70  71  72]
  [ 73  74  75  76  77  78  79  80  81  82  83  84]
  [ 85  86  87  88  89  90  91  92  93  94  95  96]
  [ 97  98  99 100 101 102 103 104 105 106 107 108]
  [109 110 111 112 113 114 115 116 117 118 119 120]]

 [[121 122 123 124 125 126 127 128 129 130 131 132]
  [133 134 135 136 137 138 139 140 141 142 143 144]
  [145 146 147 148 149 150 151 152 153 154 155 156]
  [157 158 159 160 161 162 163 164 165 166 167 168]
  [169 170 171 172 173 174 175 176 177 178 179 180]]

 [[181 182 183 184 185 186 187 188 189 190 191 192]
  [193 194 195 196 197 198 199 200 201 202 203 204]
  [205 206 207 208 209 210 211 212 213 214 215 216]
  [217 218 219 220 221 222 223 224 2

17. Generate np.arange(1, 241) and reshape it into 4 × 5 × 12. Extract layers in reverse order, the first 4 rows, and columns 12, 10, 8, 6, 4 and 2. Then create A = extracted result, B = A.copy(), and C = A.view(). Modify one element in B and one element in C. Determine exactly which arrays are affected.

In [164]:
values = np.linspace(500, 5000, 72)

arr_3d = values.reshape(3, 4, 6)
print("Original Array Shape:", arr_3d)

extracted = arr_3d[:2, 1:, ::-1]
print("Extracted Shape:", extracted)

extracted_copy = extracted.copy()

shares_mem = np.shares_memory(arr_3d, extracted_copy)
print("Does the original array share memory with the copy?", shares_mem)

if shares_mem:
    print("The copy shares memory with the original.")
else:
    print("The copy does NOT share memory with the original (they are completely independent).")

Original Array Shape: [[[ 500.          563.38028169  626.76056338  690.14084507  753.52112676
    816.90140845]
  [ 880.28169014  943.66197183 1007.04225352 1070.42253521 1133.8028169
   1197.18309859]
  [1260.56338028 1323.94366197 1387.32394366 1450.70422535 1514.08450704
   1577.46478873]
  [1640.84507042 1704.22535211 1767.6056338  1830.98591549 1894.36619718
   1957.74647887]]

 [[2021.12676056 2084.50704225 2147.88732394 2211.26760563 2274.64788732
   2338.02816901]
  [2401.4084507  2464.78873239 2528.16901408 2591.54929577 2654.92957746
   2718.30985915]
  [2781.69014085 2845.07042254 2908.45070423 2971.83098592 3035.21126761
   3098.5915493 ]
  [3161.97183099 3225.35211268 3288.73239437 3352.11267606 3415.49295775
   3478.87323944]]

 [[3542.25352113 3605.63380282 3669.01408451 3732.3943662  3795.77464789
   3859.15492958]
  [3922.53521127 3985.91549296 4049.29577465 4112.67605634 4176.05633803
   4239.43661972]
  [4302.81690141 4366.1971831  4429.57746479 4492.95774648 4556.3

18. Generate 72 equally spaced values between 500 and 5000. Reshape them into 3 × 4 × 6. Extract the first 2 layers, last 3 rows, and columns in reverse order. Create a copy of the result and use np.shares_memory() to verify whether the original and copy share memory.

In [165]:
values = np.linspace(500, 5000, 72)

arr_3d = values.reshape(3, 4, 6)
print("Original Array Shape:", arr_3d)

extracted = arr_3d[:2, 1:, ::-1]

print("Extracted Shape:", extracted)

extracted_copy = extracted.copy()

shares_mem = np.shares_memory(arr_3d, extracted_copy)
print("Does the original array share memory with the copy?", shares_mem)

if shares_mem:
    print("The copy shares memory with the original.")
else:
    print("The copy does NOT share memory with the original (they are completely independent).")

Original Array Shape: [[[ 500.          563.38028169  626.76056338  690.14084507  753.52112676
    816.90140845]
  [ 880.28169014  943.66197183 1007.04225352 1070.42253521 1133.8028169
   1197.18309859]
  [1260.56338028 1323.94366197 1387.32394366 1450.70422535 1514.08450704
   1577.46478873]
  [1640.84507042 1704.22535211 1767.6056338  1830.98591549 1894.36619718
   1957.74647887]]

 [[2021.12676056 2084.50704225 2147.88732394 2211.26760563 2274.64788732
   2338.02816901]
  [2401.4084507  2464.78873239 2528.16901408 2591.54929577 2654.92957746
   2718.30985915]
  [2781.69014085 2845.07042254 2908.45070423 2971.83098592 3035.21126761
   3098.5915493 ]
  [3161.97183099 3225.35211268 3288.73239437 3352.11267606 3415.49295775
   3478.87323944]]

 [[3542.25352113 3605.63380282 3669.01408451 3732.3943662  3795.77464789
   3859.15492958]
  [3922.53521127 3985.91549296 4049.29577465 4112.67605634 4176.05633803
   4239.43661972]
  [4302.81690141 4366.1971831  4429.57746479 4492.95774648 4556.3

19. Create an array for 4 cities, 5 days and 6 readings. Generate IDs using arange() and values using linspace(). Reshape into the required 3D structure. Select cities 2 and 4, odd-numbered days, and readings in reverse order. Store the selection, modify it, determine whether the original changed, then repeat using .copy() and compare.

In [168]:
total_elements = 4 * 5 * 6

city_ids = np.arange(1, total_elements + 1)
values = np.linspace(10, 100, total_elements)

ids_3d = city_ids.reshape(4, 5, 6)
values_3d = values.reshape(4, 5, 6)

print("Original Values 3D Shape:", values_3d)

extracted = values_3d[1:4:2, ::2, ::-1]

print("\nExtracted Selection Shape:", extracted)
print("Extracted Selection:\n", extracted)

selection_view = extracted
selection_view[0, 0, 0] = 999.0

print("\n--- View Modification Test ---")
print("Original value at corresponding position [1, 0, 5]:", values_3d[1, 0, 5])
print("Did the original array change?", values_3d[1, 0, 5] == 999.0)

extracted_fresh = values_3d[1:4:2, ::2, ::-1]
selection_copy = extracted_fresh.copy()

selection_copy[0, 0, 0] = 888.0

print("\n--- Copy Modification Test ---")
print("Original value at corresponding position [1, 0, 5]:", values_3d[1, 0, 5])
print("Did the original array change with copy?", values_3d[1, 0, 5] == 888.0)
print("Does the copy share memory with the original?", np.shares_memory(values_3d, selection_copy))

Original Values 3D Shape: [[[ 10.          10.75630252  11.51260504  12.26890756  13.02521008
    13.78151261]
  [ 14.53781513  15.29411765  16.05042017  16.80672269  17.56302521
    18.31932773]
  [ 19.07563025  19.83193277  20.58823529  21.34453782  22.10084034
    22.85714286]
  [ 23.61344538  24.3697479   25.12605042  25.88235294  26.63865546
    27.39495798]
  [ 28.1512605   28.90756303  29.66386555  30.42016807  31.17647059
    31.93277311]]

 [[ 32.68907563  33.44537815  34.20168067  34.95798319  35.71428571
    36.47058824]
  [ 37.22689076  37.98319328  38.7394958   39.49579832  40.25210084
    41.00840336]
  [ 41.76470588  42.5210084   43.27731092  44.03361345  44.78991597
    45.54621849]
  [ 46.30252101  47.05882353  47.81512605  48.57142857  49.32773109
    50.08403361]
  [ 50.84033613  51.59663866  52.35294118  53.1092437   53.86554622
    54.62184874]]

 [[ 55.37815126  56.13445378  56.8907563   57.64705882  58.40336134
    59.15966387]
  [ 59.91596639  60.67226891  61.42

20. Generate np.arange(1001, 1121) and np.linspace(40, 100, 120). Reshape both into 4 × 5 × 6. Extract the last 2 classes, first 3 subjects, and alternate students. Create a view of the scores and a copy of the IDs. Modify both and determine which original arrays change.

In [169]:
ids = np.arange(1001, 1121)
scores = np.linspace(40, 100, 120)

ids_3d = ids.reshape(4, 5, 6)
scores_3d = scores.reshape(4, 5, 6)

print("Original IDs Shape:", ids_3d)
print("Original Scores Shape:", scores_3d)

extracted_scores = scores_3d[2:, :3, ::2]
extracted_ids = ids_3d[2:, :3, ::2]

print("\nExtracted Scores Shape:", extracted_scores)

scores_view = extracted_scores.view()
ids_copy = extracted_ids.copy()

scores_view[0, 0, 0] = 999.0
ids_copy[0, 0, 0] = 8888

print("\n--- Verification ---")
print("Did the original scores_3d change?", scores_3d[2, 0, 0] == 999.0)
print("Did the original ids_3d change?", ids_3d[2, 0, 0] == 8888)

print("Does scores_view share memory with scores_3d?", np.shares_memory(scores_3d, scores_view))
print("Does ids_copy share memory with ids_3d?", np.shares_memory(ids_3d, ids_copy))

Original IDs Shape: [[[1001 1002 1003 1004 1005 1006]
  [1007 1008 1009 1010 1011 1012]
  [1013 1014 1015 1016 1017 1018]
  [1019 1020 1021 1022 1023 1024]
  [1025 1026 1027 1028 1029 1030]]

 [[1031 1032 1033 1034 1035 1036]
  [1037 1038 1039 1040 1041 1042]
  [1043 1044 1045 1046 1047 1048]
  [1049 1050 1051 1052 1053 1054]
  [1055 1056 1057 1058 1059 1060]]

 [[1061 1062 1063 1064 1065 1066]
  [1067 1068 1069 1070 1071 1072]
  [1073 1074 1075 1076 1077 1078]
  [1079 1080 1081 1082 1083 1084]
  [1085 1086 1087 1088 1089 1090]]

 [[1091 1092 1093 1094 1095 1096]
  [1097 1098 1099 1100 1101 1102]
  [1103 1104 1105 1106 1107 1108]
  [1109 1110 1111 1112 1113 1114]
  [1115 1116 1117 1118 1119 1120]]]
Original Scores Shape: [[[ 40.          40.50420168  41.00840336  41.51260504  42.01680672
    42.5210084 ]
  [ 43.02521008  43.52941176  44.03361345  44.53781513  45.04201681
    45.54621849]
  [ 46.05042017  46.55462185  47.05882353  47.56302521  48.06722689
    48.57142857]
  [ 49.0756302

21. Generate 150 equally spaced values between 10 and 1000 and arrange them into 5 × 5 × 6. Extract Layers 5, 3 and 1; Rows 4 and 2; Columns 6, 4 and 2. Find the shape of the extracted result, create a view and a copy, modify both, and check memory sharing.

In [170]:
values = np.linspace(10, 1000, 150)
arr_3d = values.reshape(5, 5, 6)
print("Original Array Shape:", arr_3d)

extracted = arr_3d[4::-2, 3:0:-2, 5:0:-2]

print("Extracted Shape:", extracted)
print("Extracted Data:\n", extracted)

extracted_view = extracted.view()
extracted_copy = extracted.copy()

extracted_view[0, 0, 0] = 999.0
extracted_copy[0, 0, 0] = 888.0

print("\n--- Memory Sharing Verification ---")
print("Does the view share memory with the original?", np.shares_memory(arr_3d, extracted_view))
print("Does the copy share memory with the original?", np.shares_memory(arr_3d, extracted_copy))

print("Did the original array change (due to view modification)?", arr_3d[4, 3, 5] == 999.0)
print("Did the original array change (due to copy modification)?", arr_3d[4, 3, 5] == 888.0)

Original Array Shape: [[[  10.           16.6442953    23.2885906    29.93288591   36.57718121
     43.22147651]
  [  49.86577181   56.51006711   63.15436242   69.79865772   76.44295302
     83.08724832]
  [  89.73154362   96.37583893  103.02013423  109.66442953  116.30872483
    122.95302013]
  [ 129.59731544  136.24161074  142.88590604  149.53020134  156.17449664
    162.81879195]
  [ 169.46308725  176.10738255  182.75167785  189.39597315  196.04026846
    202.68456376]]

 [[ 209.32885906  215.97315436  222.61744966  229.26174497  235.90604027
    242.55033557]
  [ 249.19463087  255.83892617  262.48322148  269.12751678  275.77181208
    282.41610738]
  [ 289.06040268  295.70469799  302.34899329  308.99328859  315.63758389
    322.28187919]
  [ 328.9261745   335.5704698   342.2147651   348.8590604   355.5033557
    362.14765101]
  [ 368.79194631  375.43624161  382.08053691  388.72483221  395.36912752
    402.01342282]]

 [[ 408.65771812  415.30201342  421.94630872  428.59060403  435.2

22. Create np.arange(1, 121).reshape(4, 5, 6). Without changing the original array, create a new array containing Layers 1 and 4, Rows 2, 3 and 5, and Columns 1, 3 and 5. Change all selected values in the new array to 999. Will the original array change? Explain why.

In [173]:
arr = np.arange(1, 121).reshape(4, 5, 6)

new_array = arr[np.ix_([0, 3], [1, 2, 4], [0, 2, 4])]

new_array[...] = 999

print("Does the new array share memory with the original?", np.shares_memory(arr, new_array))
print("Did any value in the original array change to 999?", np.any(arr == 999))

Does the new array share memory with the original? False
Did any value in the original array change to 999? False


23. Create 36 equally spaced values between 0 and 350 and reshape them into 6 × 6. Create: a = arr[1:5, 1:5] b = arr[1:5, 1:5].copy() Modify a[0,0] and b[0,0]. Predict the final original array before executing the program.

In [174]:
arr = np.linspace(0, 350, 36).reshape(6, 6)
print("Original Array:\n", arr)

a = arr[1:5, 1:5]
b = arr[1:5, 1:5].copy()

a[0, 0] = 999.0
b[0, 0] = 888.0

print("\nOriginal Array after modifications:\n", arr)
print("Did element arr[1,1] change to 999.0?", arr[1, 1] == 999.0)
print("Did element arr[1,1] change to 888.0?", arr[1, 1] == 888.0)

Original Array:
 [[  0.  10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100. 110.]
 [120. 130. 140. 150. 160. 170.]
 [180. 190. 200. 210. 220. 230.]
 [240. 250. 260. 270. 280. 290.]
 [300. 310. 320. 330. 340. 350.]]

Original Array after modifications:
 [[  0.  10.  20.  30.  40.  50.]
 [ 60. 999.  80.  90. 100. 110.]
 [120. 130. 140. 150. 160. 170.]
 [180. 190. 200. 210. 220. 230.]
 [240. 250. 260. 270. 280. 290.]
 [300. 310. 320. 330. 340. 350.]]
Did element arr[1,1] change to 999.0? True
Did element arr[1,1] change to 888.0? False


24. Create a dataset for 6 branches, 5 departments and 4 employees. Generate Employee IDs using arange() and Performance Scores using linspace(20, 100, ...). Reshape both into 3D. Extract Branches 6, 4 and 2; Departments 5, 3 and 1; Employees 4 and 2. Create view_data and copy_data from the extracted scores. Modify both and use np.shares_memory() to determine what happened.

In [177]:
total_elements = 6 * 5 * 4

emp_ids = np.arange(1001, 1001 + total_elements)
scores = np.linspace(20, 100, total_elements)

emp_ids_3d = emp_ids.reshape(6, 5, 4)
scores_3d = scores.reshape(6, 5, 4)

print("Original Scores Shape:", scores_3d)

extracted_scores = scores_3d[5::-2, 4::-2, 3:0:-2]
print("Extracted Scores Shape:", extracted_scores)

view_data = extracted_scores.view()
copy_data = extracted_scores.copy()

view_data[0, 0, 0] = 999.0
copy_data[0, 0, 0] = 888.0

print("\n--- Memory & Impact Verification ---")
print("Does view_data share memory with the original scores_3d?", np.shares_memory(scores_3d, view_data))
print("Does copy_data share memory with the original scores_3d?", np.shares_memory(scores_3d, copy_data))

print("Did the original scores_3d change due to view_data modification?", scores_3d[5, 4, 3] == 999.0)
print("Did the original scores_3d change due to copy_data modification?", scores_3d[5, 4, 3] == 888.0)

Original Scores Shape: [[[ 20.          20.67226891  21.34453782  22.01680672]
  [ 22.68907563  23.36134454  24.03361345  24.70588235]
  [ 25.37815126  26.05042017  26.72268908  27.39495798]
  [ 28.06722689  28.7394958   29.41176471  30.08403361]
  [ 30.75630252  31.42857143  32.10084034  32.77310924]]

 [[ 33.44537815  34.11764706  34.78991597  35.46218487]
  [ 36.13445378  36.80672269  37.4789916   38.1512605 ]
  [ 38.82352941  39.49579832  40.16806723  40.84033613]
  [ 41.51260504  42.18487395  42.85714286  43.52941176]
  [ 44.20168067  44.87394958  45.54621849  46.21848739]]

 [[ 46.8907563   47.56302521  48.23529412  48.90756303]
  [ 49.57983193  50.25210084  50.92436975  51.59663866]
  [ 52.26890756  52.94117647  53.61344538  54.28571429]
  [ 54.95798319  55.6302521   56.30252101  56.97478992]
  [ 57.64705882  58.31932773  58.99159664  59.66386555]]

 [[ 60.33613445  61.00840336  61.68067227  62.35294118]
  [ 63.02521008  63.69747899  64.3697479   65.04201681]
  [ 65.71428571  66

25. Final Challenge: Create np.arange(1, 241).reshape(4, 5, 12).
    1. Select layers 4 and 2.
    2. Select rows 5, 3 and 1.
    3. Select columns 12, 10, 8, 6, 4 and 2.
    4. Store the result.
    5. Create a view of this result.
    6. Create a copy of this result.
    7. Modify one element of the view to 999.
    8. Modify one element of the copy to 888.
    9. Print the original array, view and copy.
    10. Use np.shares_memory() to prove which arrays share memory.
    11. Explain why each modification did or did not affect the original.

In [182]:
arr = np.arange(1, 241).reshape(4, 5, 12)
print("Original Array Shape:", arr)

extracted1 = arr[3::-1, :, :]
extracted2 = arr[:, 4::-2, :]
extracted3 = arr[:, :, 11:0:-2]
print("Extracted Result Shape: \n", extracted1, "\n")
print("Extracted Result Shape: \n", extracted2, "\n")
print("Extracted Result Shape: ", extracted3, "\n")

arr_view = extracted.view()
arr_copy = extracted.copy()

arr_view[0, 0, 0] = 999
arr_copy[0, 0, 1] = 888

print("\n--- Modified View ---\n", arr_view)
print("\n--- Modified Copy ---\n", arr_copy)

print("\n--- Memory Sharing Proof (np.shares_memory) ---")
print("Does 'extracted' share memory with original 'arr'?", np.shares_memory(arr, extracted))
print("Does 'arr_view' share memory with 'extracted'?", np.shares_memory(extracted, arr_view))
print("Does 'arr_view' share memory with original 'arr'?", np.shares_memory(arr, arr_view))
print("Does 'arr_copy' share memory with 'extracted'?", np.shares_memory(extracted, arr_copy))
print("Does 'arr_copy' share memory with original 'arr'?", np.shares_memory(arr, arr_copy))

Original Array Shape: [[[  1   2   3   4   5   6   7   8   9  10  11  12]
  [ 13  14  15  16  17  18  19  20  21  22  23  24]
  [ 25  26  27  28  29  30  31  32  33  34  35  36]
  [ 37  38  39  40  41  42  43  44  45  46  47  48]
  [ 49  50  51  52  53  54  55  56  57  58  59  60]]

 [[ 61  62  63  64  65  66  67  68  69  70  71  72]
  [ 73  74  75  76  77  78  79  80  81  82  83  84]
  [ 85  86  87  88  89  90  91  92  93  94  95  96]
  [ 97  98  99 100 101 102 103 104 105 106 107 108]
  [109 110 111 112 113 114 115 116 117 118 119 120]]

 [[121 122 123 124 125 126 127 128 129 130 131 132]
  [133 134 135 136 137 138 139 140 141 142 143 144]
  [145 146 147 148 149 150 151 152 153 154 155 156]
  [157 158 159 160 161 162 163 164 165 166 167 168]
  [169 170 171 172 173 174 175 176 177 178 179 180]]

 [[181 182 183 184 185 186 187 188 189 190 191 192]
  [193 194 195 196 197 198 199 200 201 202 203 204]
  [205 206 207 208 209 210 211 212 213 214 215 216]
  [217 218 219 220 221 222 223 224 2