In [2]:
import numpy as np

In [19]:
# Create a NumPy array containing numbers from 10 to 100, with a gap of 5 between consecutive numbers.
arr = np.arange(10, 100)

print(np.linspace(10, 100, 5), "\n")
print(arr)

[ 10.   32.5  55.   77.5 100. ] 

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [21]:
# Create an array containing all even numbers from 2 to 50 using arange().
odd_num = np.arange(2, 51, 2)

print(num)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [26]:
# Create an array containing all odd numbers from 1 to 49 using arange().

even_num = np.arange(1, 50, 2)
print(even_num)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [33]:
# Create an array that contains:100, 90, 80, 70, ..., 10 using arange().

print(np.arange(100, 10, -1))

[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11]


In [35]:
# Create an array containing numbers from -20 to 20, increasing by 4.

print(np.arange(-20, 20, 4))

[-20 -16 -12  -8  -4   0   4   8  12  16]


In [44]:
# Create an array containing:5, 10, 15, 20, ..., 100 and determine its total number of elements.

arr = np.arange(5, 101, 5)

print(arr)
print(arr.size)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]
20


In [51]:
# Without manually writing the numbers, create an array containing 30 numbers starting from 7, where each next number is 3 greater than the previous number.

arr = np.arange(7, 97, 3)
print(arr)

[ 7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76
 79 82 85 88 91 94]


In [56]:
# Create an array containing numbers from 500 down to 400, decreasing by 10.

print(np.arange(500, 400, -10))

[500 490 480 470 460 450 440 430 420 410]


In [145]:
# Create an array containing the first 20 multiples of 7 using arange().

print(np.arange(7, (7 * 20 + 1), 7))

[  7  14  21  28  35  42  49  56  63  70  77  84  91  98 105 112 119 126
 133 140]


In [70]:
# Create an array of 60 elements starting from 1 and increasing by 2.

print(np.arange(1, 120, 2))

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 109 111 113 115 117 119]


In [72]:
# Generate 10 equally spaced values between 0 and 100.

print(np.linspace(0, 100, 10))

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [74]:
# Generate 21 equally spaced values between -10 and 10.

print(np.linspace(-10, 10, 21))

[-10.  -9.  -8.  -7.  -6.  -5.  -4.  -3.  -2.  -1.   0.   1.   2.   3.
   4.   5.   6.   7.   8.   9.  10.]


In [75]:
# Generate 5 equally spaced values between 50 and 100.

print(np.linspace(50, 100, 5))

[ 50.   62.5  75.   87.5 100. ]


In [77]:
# Generate 12 equally spaced values between 1 and 6.

print(np.linspace(1, 6, 12))

[1.         1.45454545 1.90909091 2.36363636 2.81818182 3.27272727
 3.72727273 4.18181818 4.63636364 5.09090909 5.54545455 6.        ]


In [79]:
# Generate 20 equally spaced values between 0 and 1.

print(np.linspace(0, 1, 20))

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [81]:
# Generate 15 equally spaced values between -50 and 50.

print(np.linspace(-50, 50, 15))

[-50.         -42.85714286 -35.71428571 -28.57142857 -21.42857143
 -14.28571429  -7.14285714   0.           7.14285714  14.28571429
  21.42857143  28.57142857  35.71428571  42.85714286  50.        ]


In [86]:
# Generate 8 equally spaced values between 10 and 80 and verify the difference between consecutive values.

print(np.linspace(10, 80, 8))

[10. 20. 30. 40. 50. 60. 70. 80.]


In [87]:
# Generate 25 equally spaced values between 100 and 200.

print(np.linspace(100, 200, 25))

[100.         104.16666667 108.33333333 112.5        116.66666667
 120.83333333 125.         129.16666667 133.33333333 137.5
 141.66666667 145.83333333 150.         154.16666667 158.33333333
 162.5        166.66666667 170.83333333 175.         179.16666667
 183.33333333 187.5        191.66666667 195.83333333 200.        ]


In [119]:
# Generate 6 equally spaced values between 5 and 30, then find the middle value.
arr = np.linspace(5, 30, 6)

print(arr, "\n")
print(arr[2 : 4])

[ 5. 10. 15. 20. 25. 30.] 

[15. 20.]


In [100]:
# Create an array of 11 equally spaced values from -1 to 1.

print(np.linspace(-1, 1, 11))

[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]


In [117]:
# Create numbers from 1 to 24 and reshape them into: (2, 3, 4)

arr = np.arange(1, 25)

print(arr, "\n")

# Explain what each dimension represents.

new_arr = np.reshape(arr, (2, 3, 4))
print(new_arr, "\n")
print(f"Dimensions {new_arr.ndim}")

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] 

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]] 

Dimensions 3


In [131]:
# Create 60 elements using arange() and reshape them into: (3, 4, 5)
arr = np.arange(60)

print(arr.reshape(3, 4, 5))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [132]:
# Create 120 elements and reshape them into: (4, 5, 6)

arr = np.arange(120)

print(arr.reshape(4, 5, 6))

[[[  0   1   2   3   4   5]
  [  6   7   8   9  10  11]
  [ 12  13  14  15  16  17]
  [ 18  19  20  21  22  23]
  [ 24  25  26  27  28  29]]

 [[ 30  31  32  33  34  35]
  [ 36  37  38  39  40  41]
  [ 42  43  44  45  46  47]
  [ 48  49  50  51  52  53]
  [ 54  55  56  57  58  59]]

 [[ 60  61  62  63  64  65]
  [ 66  67  68  69  70  71]
  [ 72  73  74  75  76  77]
  [ 78  79  80  81  82  83]
  [ 84  85  86  87  88  89]]

 [[ 90  91  92  93  94  95]
  [ 96  97  98  99 100 101]
  [102 103 104 105 106 107]
  [108 109 110 111 112 113]
  [114 115 116 117 118 119]]]


In [148]:
# Generate numbers from 1 to 36 and reshape them into: (2, 3, 6)

arr = np.arange(36)
print(arr.reshape(2, 3, 6))

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


In [158]:
# Generate 48 equally spaced values between 1 and 48 using linspace() and reshape them into: (2, 4, 6)

print(np.linspace(1, 49, 48).reshape(2, 4, 6))

[[[ 1.          2.0212766   3.04255319  4.06382979  5.08510638
    6.10638298]
  [ 7.12765957  8.14893617  9.17021277 10.19148936 11.21276596
   12.23404255]
  [13.25531915 14.27659574 15.29787234 16.31914894 17.34042553
   18.36170213]
  [19.38297872 20.40425532 21.42553191 22.44680851 23.46808511
   24.4893617 ]]

 [[25.5106383  26.53191489 27.55319149 28.57446809 29.59574468
   30.61702128]
  [31.63829787 32.65957447 33.68085106 34.70212766 35.72340426
   36.74468085]
  [37.76595745 38.78723404 39.80851064 40.82978723 41.85106383
   42.87234043]
  [43.89361702 44.91489362 45.93617021 46.95744681 47.9787234
   49.        ]]]


In [161]:
# Generate 90 values using arange() and reshape them into: (3, 5, 6)

print(np.arange(90).reshape(3, 5, 6))

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]]

 [[30 31 32 33 34 35]
  [36 37 38 39 40 41]
  [42 43 44 45 46 47]
  [48 49 50 51 52 53]
  [54 55 56 57 58 59]]

 [[60 61 62 63 64 65]
  [66 67 68 69 70 71]
  [72 73 74 75 76 77]
  [78 79 80 81 82 83]
  [84 85 86 87 88 89]]]


In [163]:
# Create an array containing 72 elements and reshape it into: (2, 6, 6)

print(np.arange(72).reshape(2, 6, 6))

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]

 [[36 37 38 39 40 41]
  [42 43 44 45 46 47]
  [48 49 50 51 52 53]
  [54 55 56 57 58 59]
  [60 61 62 63 64 65]
  [66 67 68 69 70 71]]]


In [167]:
# Create 100 elements and determine two different possible 3D shapes into which the array can be reshaped.

print(np.arange(100).reshape(5, 10, 2))

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]
  [30 31]
  [32 33]
  [34 35]
  [36 37]
  [38 39]]

 [[40 41]
  [42 43]
  [44 45]
  [46 47]
  [48 49]
  [50 51]
  [52 53]
  [54 55]
  [56 57]
  [58 59]]

 [[60 61]
  [62 63]
  [64 65]
  [66 67]
  [68 69]
  [70 71]
  [72 73]
  [74 75]
  [76 77]
  [78 79]]

 [[80 81]
  [82 83]
  [84 85]
  [86 87]
  [88 89]
  [90 91]
  [92 93]
  [94 95]
  [96 97]
  [98 99]]]


In [169]:
print(np.arange(100).reshape(5, 2, 10))

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]]

 [[20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]]

 [[40 41 42 43 44 45 46 47 48 49]
  [50 51 52 53 54 55 56 57 58 59]]

 [[60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]]

 [[80 81 82 83 84 85 86 87 88 89]
  [90 91 92 93 94 95 96 97 98 99]]]


In [173]:
print(np.arange(100).reshape(25, 2, 2))

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]

 [[20 21]
  [22 23]]

 [[24 25]
  [26 27]]

 [[28 29]
  [30 31]]

 [[32 33]
  [34 35]]

 [[36 37]
  [38 39]]

 [[40 41]
  [42 43]]

 [[44 45]
  [46 47]]

 [[48 49]
  [50 51]]

 [[52 53]
  [54 55]]

 [[56 57]
  [58 59]]

 [[60 61]
  [62 63]]

 [[64 65]
  [66 67]]

 [[68 69]
  [70 71]]

 [[72 73]
  [74 75]]

 [[76 77]
  [78 79]]

 [[80 81]
  [82 83]]

 [[84 85]
  [86 87]]

 [[88 89]
  [90 91]]

 [[92 93]
  [94 95]]

 [[96 97]
  [98 99]]]


In [176]:
print(np.arange(100).reshape(5, 5, 5))

ValueError: cannot reshape array of size 100 into shape (5,5,5)